name: class_assignments
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.3.2
  battery_plus: ^6.0.4
  connectivity_plus: ^6.1.0
  flutter_blue_plus: ^1.32.11
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_contacts: ^1.1.7
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true